# Generated by Django 3.2.11 on 2022-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_details',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
    ]
