# Generated by Django 3.2.11 on 2022-01-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hks', '0003_auto_20220130_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_details',
            name='verified',
        ),
    ]
