# Generated by Django 3.2.11 on 2022-02-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hks', '0005_rename_is_dcotor_user1_is_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='imgs')),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Physical Health', 'Physical Health'), ('Heart disease', 'Heart disease'), ('Covid', 'Covid')], max_length=20)),
                ('summary', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('as_draft', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hks.profile_details')),
            ],
        ),
    ]
